/**
 * Build script: generate binaMargaAHSP2026Official.ts from extraction JSON.
 *
 * Usage:
 *   npx tsx scripts/buildOfficialDataset.ts
 *
 * Reads : docs/_audit/lampiran2-official-items.json
 * Writes: src/data/nationalCostDatabase/binaMargaAHSP2026Official.ts
 *
 * Rules:
 * - Skip items without analisaPage (header-only, no coefficients).
 * - Map TENAGA→labor, BAHAN→material, PERALATAN→equipment.
 * - Coefficient readability: OK | TINY_COEF (<0.001) | LOST_COEF (0 with total>0).
 * - Item readability: OK (all OK) | DEGRADED (some TINY) | UNREADABLE (any LOST).
 * - unitPrice on components = example price from document (reference only).
 * - Item unitPrice = hargaSatuan (F) from document (reference only).
 * - Provenance: headerPage, analisaPage, numberFormat.
 */

import * as fs from 'fs';
import * as path from 'path';

const IN = path.resolve('docs/_audit/lampiran2-official-items.json');
const OUT = path.resolve('src/data/nationalCostDatabase/binaMargaAHSP2026Official.ts');

interface OfficialComponent {
  componentType: 'TENAGA' | 'BAHAN' | 'PERALATAN';
  index: number;
  name: string;
  code: string;
  unit: string;
  coefficient: number;
  unitPrice: number;
  total: number;
  raw: string;
}

interface OfficialItem {
  serial: string;
  code: string;
  codeNormalized: string;
  name: string;
  unit: string;
  headerPage: number;
  analisaPage: number | null;
  numberFormat: 'ID' | 'US' | null;
  components: OfficialComponent[];
  totalLabor: number | null;
  totalMaterial: number | null;
  totalEquipment: number | null;
  totalABC: number | null;
  overheadProfitPercent: number | null;
  overheadProfitAmount: number | null;
  hargaSatuan: number | null;
  warnings: string[];
}

function classifyCoefficient(c: OfficialComponent): 'OK' | 'TINY_COEF' | 'LOST_COEF' {
  if (c.coefficient === 0 && c.total > 0) return 'LOST_COEF';
  if (c.coefficient < 0.001) return 'TINY_COEF';
  return 'OK';
}

function classifyItem(components: OfficialComponent[]): 'OK' | 'DEGRADED' | 'UNREADABLE' {
  const flags = components.map(classifyCoefficient);
  if (flags.includes('LOST_COEF')) return 'UNREADABLE';
  if (flags.includes('TINY_COEF')) return 'DEGRADED';
  return 'OK';
}

function scoreItem(item: OfficialItem, readability: 'OK' | 'DEGRADED' | 'UNREADABLE'): number {
  if (readability === 'UNREADABLE') return 0;
  if (readability === 'DEGRADED') return 60;
  if (item.warnings.length > 0) return 85;
  return 100;
}

function escapeString(s: string | null | undefined): string {
  if (s == null) return '';
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function fmtNum(n: number | null): string {
  if (n === null) return 'null';
  if (!Number.isFinite(n)) return 'null';
  return String(n);
}

function build() {
  const data: { items: OfficialItem[] } = JSON.parse(fs.readFileSync(IN, 'utf8'));

  const items = data.items.filter((i) => i.analisaPage !== null);

  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by scripts/buildOfficialDataset.ts`);
  lines.push(`// Source: ${IN}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`// Items: ${items.length}`);
  lines.push(`//`);
  lines.push(`// This file ONLY contains the data array.  Types and metadata live in`);
  lines.push(`// binaMargaAHSP2026OfficialTypes.ts to avoid cyclic imports.`);
  lines.push(`import type { OfficialAHSPItem } from './binaMargaAHSP2026OfficialTypes';`);
  lines.push(`
// ---------------------------------------------------------------------------
// DATA BEGINS
// ---------------------------------------------------------------------------
`);

  lines.push(`export const BINA_MARGA_AHSP_2026_OFFICIAL: OfficialAHSPItem[] = [`);

  for (let idx = 0; idx < items.length; idx++) {
    const it = items[idx];
    const readability = classifyItem(it.components);
    const score = scoreItem(it, readability);
    const id = `BM-2026-${String(idx + 1).padStart(5, '0')}`;

    const labor = it.components.filter((c) => c.componentType === 'TENAGA');
    const material = it.components.filter((c) => c.componentType === 'BAHAN');
    const equipment = it.components.filter((c) => c.componentType === 'PERALATAN');

    const compLines = (arr: OfficialComponent[]) =>
      arr
        .map(
          (c) =>
            `      { id: '${id}-C${c.index}', code: '${escapeString(c.code || '')}', name: '${escapeString(c.name)}', unit: '${escapeString(c.unit)}', coefficient: ${fmtNum(c.coefficient)}, unitPrice: ${fmtNum(c.unitPrice)}, total: ${fmtNum(c.total)}, index: ${c.index}, componentType: '${c.componentType}', readability: '${classifyCoefficient(c)}', raw: '${escapeString(c.raw)}' }`,
        )
        .join(',\n');

    lines.push(`  {`);
    lines.push(`    id: '${id}',`);
    lines.push(`    code: '${escapeString(it.code)}',`);
    lines.push(`    codeNormalized: '${escapeString(it.codeNormalized)}',`);
    lines.push(`    name: '${escapeString(it.name)}',`);
    lines.push(`    unit: '${escapeString(it.unit)}',`);
    lines.push(`    domain: 'BINA_MARGA',`);
    lines.push(`    category: 'PEKERJAAN BINA MARGA',`);
    lines.push(`    version: '2026',`);
    lines.push(`    year: 2026,`);
    lines.push(`    normativeStatus: 'Normatif',`);
    lines.push(`    method: 'Manual',`);
    lines.push(`    sourceDocument: 'Lampiran II SE DJBK No. 47/SE/Dk/2026',`);
    lines.push(`    headerPage: ${it.headerPage},`);
    lines.push(`    analisaPage: ${it.analisaPage},`);
    lines.push(`    numberFormat: ${it.numberFormat ? `'${it.numberFormat}'` : 'null'},`);
    lines.push(`    status: 'VERIFIED',`);
    lines.push(`    laborComponents: [`);
    if (labor.length) lines.push(compLines(labor));
    lines.push(`    ],`);
    lines.push(`    materialComponents: [`);
    if (material.length) lines.push(compLines(material));
    lines.push(`    ],`);
    lines.push(`    equipmentComponents: [`);
    if (equipment.length) lines.push(compLines(equipment));
    lines.push(`    ],`);
    lines.push(`    totalLabor: ${fmtNum(it.totalLabor)},`);
    lines.push(`    totalMaterial: ${fmtNum(it.totalMaterial)},`);
    lines.push(`    totalEquipment: ${fmtNum(it.totalEquipment)},`);
    lines.push(`    totalABC: ${fmtNum(it.totalABC)},`);
    lines.push(`    overheadProfitPercent: ${fmtNum(it.overheadProfitPercent)},`);
    lines.push(`    overheadProfitAmount: ${fmtNum(it.overheadProfitAmount)},`);
    lines.push(`    unitPrice: ${fmtNum(it.hargaSatuan)},`);
    lines.push(`    readability: '${readability}',`);
    lines.push(`    warnings: [${it.warnings.map((w) => `'${escapeString(w)}'`).join(', ')}],`);
    lines.push(`    lastUpdated: '${new Date().toISOString().slice(0, 10)}',`);
    lines.push(`    dataQualityScore: ${score},`);
    lines.push(`  }${idx < items.length - 1 ? ',' : ''}`);
  }

  lines.push(`];`);

  fs.writeFileSync(OUT, lines.join('\n'), 'utf8');
  console.log(`Wrote ${items.length} items to ${OUT}`);
}

build();
