"""Build cleanup-manifest-before-delete.json. Read-only (writes only the manifest)."""
import os, json, hashlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

def sha256(p):
    try:
        h = hashlib.sha256()
        with open(p, 'rb') as fh:
            for c in iter(lambda: fh.read(1 << 20), b''):
                h.update(c)
        return h.hexdigest()
    except OSError:
        return None

def size_of(p):
    if os.path.isfile(p):
        return os.path.getsize(p)
    if os.path.isdir(p):
        t = 0
        for dp, dn, fn in os.walk(p):
            for f in fn:
                try:
                    t += os.path.getsize(os.path.join(dp, f))
                except OSError:
                    pass
        return t
    return 0

def count_of(p):
    if os.path.isfile(p):
        return 1
    if os.path.isdir(p):
        n = 0
        for dp, dn, fn in os.walk(p):
            n += len(fn)
        return n
    return 0

# (path, category, reason, references, confidence)
ENTRIES = [
    # --- E: GENERATED / REBUILDABLE ---
    ('dist', 'E_GENERATED', 'Vite production build output; regenerated by `npm run build`. No deploy config or server references it.', [], 0.99),
    ('dist-qa', 'E_GENERATED', 'Stale QA build output (Sep 23). Unreferenced by any script/config; only appears in a SKIP_DIRS list. Not produced by `npm run build`.', ['scripts/price2026/zeroPriceForensic.ts (SKIP_DIRS only)'], 0.98),
    # --- F: CACHE ---
    ('node_modules/.vite-temp', 'F_CACHE', 'Vite temporary config bundles left over from interrupted builds. Regenerated on every `vite` run.', [], 0.99),
    ('node_modules/.vite', 'F_CACHE', 'Vite dependency pre-bundle cache. Regenerated on next dev/build.', [], 0.99),
    ('EZRAB-LOCAL-AI/__pycache__', 'F_CACHE', 'Python bytecode cache. Regenerated on import.', [], 0.99),
    # --- G: TEMPORARY ---
    ('tmp', 'G_TEMPORARY', 'Build/test scratch logs (.out/.err/.pid/.cmd) from prior sessions.', [], 0.98),
    # --- H: DUPLICATE ---
    ('bina_marga_downloaded.pdf', 'H_DUPLICATE', 'SHA256-identical to sources/ahsp2026/Lampiran-V-SE-DJBK-No-47-Tahun-2026-AHSP-Bidang-Bina-Marga.pdf (canonical retained).', ['sources/ahsp2026/Lampiran-V-...-Bina-Marga.pdf (identical)'], 0.98),
    ('Lampiran-II-SE-DJBK-No-47-Tahun-2026-AHSP-Bidang-Bina-Marga.pdf', 'H_DUPLICATE', 'SHA256-identical to sources/ahsp2026/Lampiran-V-...-Bina-Marga.pdf. Root copy is mis-named (Lampiran II != Bina Marga).', ['sources/ahsp2026/Lampiran-V-...-Bina-Marga.pdf (identical)'], 0.98),
    ('EZRAB_VOLUME_CALCULATOR_MASTER_COPY.xlsx', 'H_DUPLICATE', 'SHA256-identical to EZRAB_VOLUME_CALCULATOR_MASTER.xlsx (canonical retained, 20 refs).', ['EZRAB_VOLUME_CALCULATOR_MASTER.xlsx (identical)'], 0.97),
    ('qa-fixtures/pdf-gambar-rumah-1-lantai_compress.pdf', 'H_DUPLICATE', 'SHA256-identical to public/samples/pdf-gambar-rumah-1-lantai_compress.pdf (served copy retained).', ['public/samples/pdf-gambar-rumah-1-lantai_compress.pdf (identical)'], 0.97),
    ('video.png', 'H_DUPLICATE', 'SHA256-identical to public/images/construction-cinematic.png (used by UI).', ['public/images/construction-cinematic.png (identical)'], 0.97),
    # --- I: OBSOLETE ---
    ('phase1_1_workbook_inventory.json', 'I_OBSOLETE', 'Phase-1 audit dump. Referenced only by two historical markdown logs, not by code.', ['PHASE1_1_REMEDIATION_LOG.md', 'PHASE1_1_WORKBOOK_AUDIT.md'], 0.96),
    ('phase3_workbook_inventory.json', 'I_OBSOLETE', 'Phase-3 audit dump. Referenced only by historical markdown.', [], 0.96),
    ('all_19_calculators_raw.json', 'I_OBSOLETE', 'Raw calculator scrape used to author the registry spec; superseded by src calculator registry.', [], 0.95),
    ('audit_meta_sheets.json', 'I_OBSOLETE', 'Workbook metadata dump from a past audit. Not read by any script.', [], 0.95),
    ('ezrab_downloaded.html', 'I_OBSOLETE', 'Downloaded page snapshot consumed only by one-off root scripts extract_full.py / inspect_html.py.', ['extract_full.py', 'inspect_html.py'], 0.95),
    ('EZRAB-LOCAL-AI/python-3.12.10-amd64.exe', 'I_OBSOLETE', 'Python installer; the runtime is already extracted in EZRAB-LOCAL-AI/.python. Re-downloadable from python.org.', [], 0.95),
    ('EZRAB-LOCAL-AI/main.memory-aware-chat.backup-20260912.py', 'I_OBSOLETE', 'Dated .backup-20260912 source snapshot superseded by main.py.', [], 0.97),
    ('EZRAB-LOCAL-AI/main.orchestrator-step3.backup-20260912.py', 'I_OBSOLETE', 'Dated .backup-20260912 source snapshot superseded by main.py.', [], 0.97),
    ('EZRAB-LOCAL-AI/main.provider-step2.backup-20260912.py', 'I_OBSOLETE', 'Dated .backup-20260912 source snapshot superseded by main.py.', [], 0.97),
    ('EZRAB-LOCAL-AI/main_backup_v0.2.py', 'I_OBSOLETE', 'v0.2 backup superseded by main.py.', [], 0.96),
]

def main():
    # Root QA screenshots: unreferenced transient test evidence
    listed = {p.replace('\\', '/') for p, *_ in ENTRIES}
    root_imgs = []
    for f in os.listdir(ROOT):
        if os.path.isfile(os.path.join(ROOT, f)) and f.lower().endswith(('.png', '.jpg', '.jpeg')):
            if f not in listed:
                root_imgs.append(f)
    for f in sorted(root_imgs):
        ENTRIES.append((f, 'G_TEMPORARY', 'Root-level QA/browser-proof screenshot or scratch render. Not embedded in any markdown, not imported by code.', [], 0.95))

    manifest = []
    total = 0
    for path, cat, reason, refs, conf in ENTRIES:
        ap = os.path.join(ROOT, path)
        if not os.path.exists(ap):
            continue
        s = size_of(ap)
        total += s
        entry = {
            'path': path.replace('\\', '/'),
            'size_bytes': s,
            'size_mb': round(s / 1048576, 3),
            'files': count_of(ap),
            'category': cat,
            'reason': reason,
            'references': refs,
            'confidence': conf,
        }
        if os.path.isfile(ap) and s < 8 * 1024 * 1024:
            entry['sha256'] = sha256(ap)
        manifest.append(entry)

    manifest.sort(key=lambda e: -e['size_bytes'])
    out = {
        'root': ROOT.replace('\\', '/'),
        'generated_at': '2026-10-04',
        'policy': 'Delete only confidence >= 0.95. Preserve A/B/C (runtime, source data, dev) and all AHSP/DED/AI critical data.',
        'entry_count': len(manifest),
        'total_bytes': total,
        'total_mb': round(total / 1048576, 2),
        'entries': manifest,
    }
    with open(os.path.join(ROOT, 'scripts', 'cleanup', 'cleanup-manifest-before-delete.json'), 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1)

    print(f"MANIFEST: {len(manifest)} entries, {out['total_mb']:,.2f} MB")
    print()
    by_cat = {}
    for e in manifest:
        c = by_cat.setdefault(e['category'], [0, 0])
        c[0] += 1
        c[1] += e['size_bytes']
    for k in sorted(by_cat):
        n, b = by_cat[k]
        print(f"  {k:<16} {n:>4} entries  {b/1048576:>10,.2f} MB")
    print()
    for e in manifest:
        print(f"{e['size_mb']:>9,.3f} MB  [{e['category']:<12}] c={e['confidence']}  {e['path']}")

if __name__ == '__main__':
    main()
