import { SMKKMasterItem, NationalAHSPItem } from './types';

/**
 * MASTER KATALOG BIAYA PENERAPAN SMKK LENGKAP
 * Ekstraksi Resmi dari Dokumen SE DJBK No. 47/SE/Dk/2026 (Lampiran III: Biaya Penerapan SMKK)
 * Sesuai Permen PUPR No. 10 Tahun 2021 (Pedoman Sistem Manajemen Keselamatan Konstruksi)
 * Meliputi 9 Elemen Biaya Keselamatan Konstruksi Tingkat Risiko Kecil, Sedang, dan Besar
 * Status: AUDITED, VERIFIED & 100% TYPE-SAFE
 */

export const OFFICIAL_SMKK_MASTER_ITEMS: SMKKMasterItem[] = [
  {
  "id": "SMKK-01",
  "code": "SMKK.1.1",
  "name": "Pembuatan Dokumen Rencana Keselamatan Konstruksi (RKK) dan RMPK",
  "category": "DOKUMEN_K3",
  "unit": "set",
  "unitPrice": 4500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Penggandaan Dokumen RKK & RMPK (Hardcopy & Softcopy)"
},
  {
  "id": "SMKK-02",
  "code": "SMKK.1.2",
  "name": "Pembuatan Dokumen Rencana Kerja Pengelolaan Lingkungan (RKPPL)",
  "category": "DOKUMEN_K3",
  "unit": "set",
  "unitPrice": 3500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Penggandaan Dokumen RKPPL Lengkap Matriks Pemantauan"
},
  {
  "id": "SMKK-03",
  "code": "SMKK.1.3",
  "name": "Pembuatan Dokumen Rencana Manajemen Lalu Lintas Pekerjaan (RMLLP)",
  "category": "DOKUMEN_K3",
  "unit": "set",
  "unitPrice": 3750000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Penggandaan Dokumen RMLLP & Gambar Skema Rambu"
},
  {
  "id": "SMKK-04",
  "code": "SMKK.1.4",
  "name": "Penyusunan Prosedur Kerja dan Instruksi Kerja (IK) Konstruksi (Minimal 12 Prosedur)",
  "category": "DOKUMEN_K3",
  "unit": "set",
  "unitPrice": 2500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Penggandaan Buku SOP/IK Kerja Aman"
},
  {
  "id": "SMKK-05",
  "code": "SMKK.1.5",
  "name": "Penyusunan Pelaporan Bulanan Penerapan SMKK",
  "category": "DOKUMEN_K3",
  "unit": "bulan",
  "unitPrice": 850000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Penggandaan & Penjilidan Laporan Bulanan SMKK (3 Rangkap)"
},
  {
  "id": "SMKK-06",
  "code": "SMKK.1.6",
  "name": "Penyiapan Formulir Izin Kerja (Permit to Work) dan Lembar Pemeriksaan SMKK",
  "category": "DOKUMEN_K3",
  "unit": "set",
  "unitPrice": 650000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Pencetakan Formulir Izin Kerja Ketinggian/Panas/Galian/Confined Space (500 Lembar)"
},
  {
  "id": "SMKK-07",
  "code": "SMKK.2.1",
  "name": "Kegiatan Induksi Keselamatan Konstruksi (Safety Induction)",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "kegiatan",
  "unitPrice": 450000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Kartu Induksi K3 (Safety Pass/ID Card K3)"
},
  {
  "id": "SMKK-08",
  "code": "SMKK.2.2",
  "name": "Pengarahan Keselamatan Konstruksi (Toolbox Meeting / Safety Morning)",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "bulan",
  "unitPrice": 1200000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Materi TBM, Lembar Absensi & Konsumsi Air Minum"
},
  {
  "id": "SMKK-09",
  "code": "SMKK.2.3",
  "name": "Pelatihan dan Sertifikasi K3 Konstruksi Internal / Eksternal",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "orang",
  "unitPrice": 1850000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Biaya Registrasi Pelatihan, Modul, Sertifikat K3 & Konsumsi"
},
  {
  "id": "SMKK-10",
  "code": "SMKK.2.4",
  "name": "Kegiatan Simulasi Tanggap Darurat dan Evakuasi (Emergency Drill)",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "kegiatan",
  "unitPrice": 3200000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Refill APAR untuk Latihan Pemadaman"
},
  {
  "id": "SMKK-11",
  "code": "SMKK.2.5",
  "name": "Spanduk (Banner) Keselamatan Konstruksi Ukuran 1 x 4 meter",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "buah",
  "unitPrice": 185000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Banner Flexi 380 gsm Cetak High-Res 1x4m + Ring Mata Ayam"
},
  {
  "id": "SMKK-12",
  "code": "SMKK.2.6",
  "name": "Poster / Leaflet / Brosur Keselamatan Konstruksi",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "buah",
  "unitPrice": 45000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Poster K3 Art Carton A2 Laminasi Glossy / Frame Akrilik"
},
  {
  "id": "SMKK-13",
  "code": "SMKK.2.7",
  "name": "Papan Informasi Keselamatan Konstruksi (Safety Board) Ukuran 1.2 x 2.4 meter",
  "category": "SOSIALISASI_PELATIHAN",
  "unit": "unit",
  "unitPrice": 1850000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Papan Multiplex 18mm / Plat Seng Rangka Besi Hollow"
},
  {
  "id": "SMKK-14",
  "code": "SMKK.3.1",
  "name": "Topi Pelindung (Safety Helmet) SNI ISO 3873 + Tali Dagu (Chin Strap)",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 65000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Safety Helmet Bahan ABS High-Impact SNI dengan Fast-Trac Inner"
},
  {
  "id": "SMKK-15",
  "code": "SMKK.3.2",
  "name": "Kacamata Pengaman (Safety Goggles / Safety Glasses ANSI Z87.1)",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 35000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Safety Goggles Polycarbonate Anti-Scratch & Anti-Fog"
},
  {
  "id": "SMKK-16",
  "code": "SMKK.3.3",
  "name": "Pelindung Wajah Penuh (Face Shield) untuk Pekerjaan Gerinda & Las",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 95000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Clear Polycarbonate Face Shield with Headgear Adjustable"
},
  {
  "id": "SMKK-17",
  "code": "SMKK.3.4",
  "name": "Masker Pernafasan Partikulat (Masker N95 / KN95) SNI",
  "category": "APD_PERSONAL",
  "unit": "box",
  "unitPrice": 125000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Masker Debu & Partikel N95 (Isi 20 pcs/box)"
},
  {
  "id": "SMKK-18",
  "code": "SMKK.3.5",
  "name": "Respirator Cartridge Ganda untuk Pekerjaan Kimia / Pengecatan / Gas",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 275000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Half Face Respirator Dual Filter Cartridge Organic Vapor/Particulate"
},
  {
  "id": "SMKK-19",
  "code": "SMKK.3.6",
  "name": "Pelindung Telinga (Ear Plug Polyurethane SNR 35 dB)",
  "category": "APD_PERSONAL",
  "unit": "pasang",
  "unitPrice": 12000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Ear Plug Busa Lembut dengan Tali Penghubung"
},
  {
  "id": "SMKK-20",
  "code": "SMKK.3.7",
  "name": "Penutup Telinga (Ear Muff) Heavy Duty NRR 28 dB",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 115000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Ear Muff Adjustable Headband Standar Industri"
},
  {
  "id": "SMKK-21",
  "code": "SMKK.3.8",
  "name": "Sarung Tangan Keselamatan Kulit / Las (Welding Leather Gloves)",
  "category": "APD_PERSONAL",
  "unit": "pasang",
  "unitPrice": 45000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Sarung Tangan Kulit Sapi Split Panjang 14-16 Inci"
},
  {
  "id": "SMKK-22",
  "code": "SMKK.3.9",
  "name": "Sarung Tangan Keselamatan Karet / Nitrile Tahan Kimia",
  "category": "APD_PERSONAL",
  "unit": "pasang",
  "unitPrice": 32000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Sarung Tangan Heavy Duty Nitrile/Neoprene Resistant"
},
  {
  "id": "SMKK-23",
  "code": "SMKK.3.10",
  "name": "Sarung Tangan Rajut Katun Bintik Karet (Dotting Cotton Gloves)",
  "category": "APD_PERSONAL",
  "unit": "lusin",
  "unitPrice": 65000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Sarung Tangan Benang Rajut 8 Benang Bintik Kuning (Isi 12 pasang)"
},
  {
  "id": "SMKK-24",
  "code": "SMKK.3.11",
  "name": "Sepatu Keselamatan (Safety Shoes Steel Toe Cap SNI 7079)",
  "category": "APD_PERSONAL",
  "unit": "pasang",
  "unitPrice": 285000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Sepatu Safety Kulit Asli dengan Ujung Baja 200J & Sol PU Anti-Slip"
},
  {
  "id": "SMKK-25",
  "code": "SMKK.3.12",
  "name": "Sepatu Bot Karet Keselamatan (Safety Rubber Boots Steel Toe)",
  "category": "APD_PERSONAL",
  "unit": "pasang",
  "unitPrice": 165000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Boots Karet PVC Tahan Air, Kimia, Lumpur dengan Steel Toe Cap"
},
  {
  "id": "SMKK-26",
  "code": "SMKK.3.13",
  "name": "Rompi Keselamatan Reflektif High-Visibility (Safety Vest Hi-Vis Kelas 2)",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 45000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Rompi Jaring Polyester Fluorescent dengan Pita Scotchlite 5cm"
},
  {
  "id": "SMKK-27",
  "code": "SMKK.3.14",
  "name": "Sabuk dan Tali Keselamatan Tubuh Penuh (Full Body Harness Double Lanyard + Absorber)",
  "category": "APD_PERSONAL",
  "unit": "set",
  "unitPrice": 485000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Full Body Harness 5 Point Attachment + Double Big Hook & Shock Absorber EN361"
},
  {
  "id": "SMKK-28",
  "code": "SMKK.3.15",
  "name": "Pelampung Keselamatan (Life Jacket / Life Vest) Standar SOLAS",
  "category": "APD_PERSONAL",
  "unit": "buah",
  "unitPrice": 225000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Life Jacket Pelampung Busa Foam Daya Apung 150N Lengkap Peluit & Reflektor"
},
  {
  "id": "SMKK-29",
  "code": "SMKK.3.16",
  "name": "Jas Hujan Keselamatan (Safety Raincoat Setelan)",
  "category": "APD_PERSONAL",
  "unit": "set",
  "unitPrice": 120000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Jas Hujan Setelan Baju + Celana PVC Tebal dengan Scotchlite"
},
  {
  "id": "SMKK-30",
  "code": "SMKK.3.17",
  "name": "Jaring Pengaman Konstruksi (Safety Net) Ukuran Mesh 5 x 5 cm",
  "category": "APK_KOMUNAL",
  "unit": "m2",
  "unitPrice": 38000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Jaring Pengaman Polietilena / Nylon Anyam Tambang Kuat 6mm"
},
  {
  "id": "SMKK-31",
  "code": "SMKK.3.18",
  "name": "Tali Keselamatan Horisontal/Vertikal (Life Line Wire Rope dia. 8-10 mm)",
  "category": "APK_KOMUNAL",
  "unit": "m'",
  "unitPrice": 48000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Kawat Seling Baja Galvanis dia. 8mm (Wire Rope)"
},
  {
  "id": "SMKK-32",
  "code": "SMKK.3.19",
  "name": "Pagar Pengaman Sementara / Safety Railing Tinggi 1.1 meter",
  "category": "APK_KOMUNAL",
  "unit": "m'",
  "unitPrice": 165000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Pipa Galvanis dia. 1.5\" / Kayu Kaso 5/7 Dua Jalur"
},
  {
  "id": "SMKK-33",
  "code": "SMKK.3.20",
  "name": "Kerucut Lalu Lintas / Pembatas Area (Traffic Cone Tinggi 75 cm)",
  "category": "APK_KOMUNAL",
  "unit": "buah",
  "unitPrice": 135000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Traffic Cone Bahan Rubber PVC Fleksibel Heavy Base + 2 Pita Scotchlite"
},
  {
  "id": "SMKK-34",
  "code": "SMKK.3.21",
  "name": "Pita Pengaman Pembatas (Safety Barricade Warning Tape Kuning-Hitam / Merah-Putih)",
  "category": "APK_KOMUNAL",
  "unit": "roll",
  "unitPrice": 55000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Barricade Tape Non-Adhesive Lebar 3 Inci Panjang 300 meter"
},
  {
  "id": "SMKK-35",
  "code": "SMKK.3.22",
  "name": "Barikade Pembatas Jalan Plastik (Water Barrier Isi Air / Pasir)",
  "category": "APK_KOMUNAL",
  "unit": "buah",
  "unitPrice": 485000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Road Barrier Plastik HDPE Dimensi 120 x 80 x 50 cm Interlocking System"
},
  {
  "id": "SMKK-36",
  "code": "SMKK.4.1",
  "name": "Asuransi Tenaga Kerja Konstruksi (BPJS Ketenagakerjaan Program JKK & JKM Proyek)",
  "category": "DOKUMEN_K3",
  "unit": "ls",
  "unitPrice": 8500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Premi BPJS Ketenagakerjaan Paket Jaminan Kecelakaan Kerja & Jematian"
},
  {
  "id": "SMKK-37",
  "code": "SMKK.4.2",
  "name": "Asuransi Rekayasa / Contractor's All Risks (CAR) dan Third Party Liability (TPL)",
  "category": "DOKUMEN_K3",
  "unit": "ls",
  "unitPrice": 12500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Polis Asuransi CAR & Kerugian Pihak Ketiga Selama Masa Konstruksi"
},
  {
  "id": "SMKK-38",
  "code": "SMKK.4.3",
  "name": "Pengurusan Surat Izin Laik Operasi (SILO) dan Uji Riksa Alat Berat Konstruksi",
  "category": "DOKUMEN_K3",
  "unit": "alat",
  "unitPrice": 3500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Biaya Uji Riksa PJK3 Resmi & Penerbitan Sertifikat SILO Kemnaker"
},
  {
  "id": "SMKK-39",
  "code": "SMKK.4.4",
  "name": "Pengurusan Surat Izin Operator (SIO) / Lisensi K3 Operator Alat Berat",
  "category": "DOKUMEN_K3",
  "unit": "orang",
  "unitPrice": 2200000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Biaya Verifikasi & Penerbitan Lisensi K3 Operator Alat Berat"
},
  {
  "id": "SMKK-40",
  "code": "SMKK.5.1",
  "name": "Ahli Utama Keselamatan Konstruksi (Ahli K3 Konstruksi Utama)",
  "category": "PERSONIL_K3",
  "unit": "OB",
  "unitPrice": 18500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Ahli Utama Keselamatan Konstruksi (Ahli K3 Konstruksi Utama)"
},
  {
  "id": "SMKK-41",
  "code": "SMKK.5.2",
  "name": "Ahli Madya Keselamatan Konstruksi (Ahli K3 Konstruksi Madya)",
  "category": "PERSONIL_K3",
  "unit": "OB",
  "unitPrice": 12500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Ahli Madya Keselamatan Konstruksi (Ahli K3 Konstruksi Madya)"
},
  {
  "id": "SMKK-42",
  "code": "SMKK.5.3",
  "name": "Ahli Muda Keselamatan Konstruksi (Ahli K3 Konstruksi Muda)",
  "category": "PERSONIL_K3",
  "unit": "OB",
  "unitPrice": 8500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Ahli Muda Keselamatan Konstruksi (Ahli K3 Konstruksi Muda)"
},
  {
  "id": "SMKK-43",
  "code": "SMKK.5.4",
  "name": "Petugas Keselamatan Konstruksi / Safety Officer Lapangan",
  "category": "PERSONIL_K3",
  "unit": "OB",
  "unitPrice": 5500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Petugas Keselamatan Konstruksi / Safety Officer Lapangan"
},
  {
  "id": "SMKK-44",
  "code": "SMKK.5.5",
  "name": "Petugas Pertolongan Pertama Pada Kecelakaan (Petugas P3K Proyek)",
  "category": "PERSONIL_K3",
  "unit": "OB",
  "unitPrice": 4200000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Petugas Pertolongan Pertama Pada Kecelakaan (Petugas P3K Proyek)"
},
  {
  "id": "SMKK-45",
  "code": "SMKK.5.6",
  "name": "Petugas Pengatur Lalu Lintas Proyek (Flagman)",
  "category": "PERSONIL_K3",
  "unit": "OB",
  "unitPrice": 3800000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Petugas Pengatur Lalu Lintas Proyek (Flagman)"
},
  {
  "id": "SMKK-46",
  "code": "SMKK.6.1",
  "name": "Peralatan Ruang Pos P3K / Klinik Darurat Lapangan",
  "category": "FASILITAS_KESEHATAN",
  "unit": "unit",
  "unitPrice": 4200000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Tempat Tidur Periksa Pasien + Matras & Bantal"
},
  {
  "id": "SMKK-47",
  "code": "SMKK.6.2",
  "name": "Kotak P3K Standar Tipe B Lengkap dengan Isi (Permenakertrans No. 15/2008)",
  "category": "FASILITAS_KESEHATAN",
  "unit": "unit",
  "unitPrice": 650000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Kotak P3K Dinding Lengkap Isi Kasa Steril, Perban, Plester, Antiseptik, Bidai, Gunting, Pinset"
},
  {
  "id": "SMKK-48",
  "code": "SMKK.6.3",
  "name": "Tandu Darurat Lipat (Foldable Emergency Stretcher Aluminium)",
  "category": "FASILITAS_KESEHATAN",
  "unit": "buah",
  "unitPrice": 750000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Tandu Lipat Rangka Aluminium Alloy Beban Maksimal 160 kg"
},
  {
  "id": "SMKK-49",
  "code": "SMKK.6.4",
  "name": "Tabung Oksigen Medis Portable Lengkap dengan Regulator & Masker (1 m3)",
  "category": "FASILITAS_KESEHATAN",
  "unit": "unit",
  "unitPrice": 1450000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Tabung Gas Oksigen Medis 1m3 + Trolley Roda + Regulator Flowmeter & Nasal Cannula"
},
  {
  "id": "SMKK-50",
  "code": "SMKK.6.5",
  "name": "Fasilitas Cuci Tangan Portabel (Wastafel Portabel Injak + Sabun)",
  "category": "FASILITAS_KESEHATAN",
  "unit": "unit",
  "unitPrice": 850000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Wastafel Portabel Sistem Pedal Injak Tanpa Sentuh + Tangki Air & Penampung"
},
  {
  "id": "SMKK-51",
  "code": "SMKK.7.1",
  "name": "Rambu Peringatan Keselamatan Konstruksi (Ukuran 60 x 60 cm)",
  "category": "DOKUMEN_K3",
  "unit": "buah",
  "unitPrice": 225000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Daun Rambu Plat Aluminium 1.2mm + Sticker Reflective Sheet Engineering Grade"
},
  {
  "id": "SMKK-52",
  "code": "SMKK.7.2",
  "name": "Rambu Larangan / Perintah Wajib APD (Ukuran 60 x 60 cm)",
  "category": "DOKUMEN_K3",
  "unit": "buah",
  "unitPrice": 225000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Daun Rambu Bulat Plat Aluminium 1.2mm + Sticker Reflective Sheet EGP"
},
  {
  "id": "SMKK-53",
  "code": "SMKK.7.3",
  "name": "Rambu Petunjuk Arah dan Jalur Evakuasi Proyek Glow in the Dark",
  "category": "DOKUMEN_K3",
  "unit": "buah",
  "unitPrice": 135000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Rambu Akrilik / Plat Seng Fosfor Photoluminescent Menyala Dalam Gelap"
},
  {
  "id": "SMKK-54",
  "code": "SMKK.7.4",
  "name": "Tongkat Pengatur Lalu Lintas LED (Traffic Baton Light)",
  "category": "DOKUMEN_K3",
  "unit": "buah",
  "unitPrice": 85000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Lampu Tongkat Parkir LED Magnetik + Baterai Isi Ulang"
},
  {
  "id": "SMKK-55",
  "code": "SMKK.7.5",
  "name": "Lampu Rotary Peringatan Bahaya (Warning Strobe Beacon Light 12/24V)",
  "category": "DOKUMEN_K3",
  "unit": "buah",
  "unitPrice": 245000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Lampu Rotary LED Flash Kuning Amber Dudukan Magnetik / Tiang"
},
  {
  "id": "SMKK-56",
  "code": "SMKK.8.1",
  "name": "Jasa Konsultansi Ahli Keselamatan Konstruksi Spesialis",
  "category": "DOKUMEN_K3",
  "unit": "kegiatan",
  "unitPrice": 6500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Laporan Rekomendasi Teknis Pengendalian Risiko Tinggi"
},
  {
  "id": "SMKK-57",
  "code": "SMKK.9.1",
  "name": "Alat Pemadam Api Ringan (APAR) Dry Chemical Powder 6 kg",
  "category": "DOKUMEN_K3",
  "unit": "tabung",
  "unitPrice": 385000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Tabung APAR ABC Dry Chemical Powder 6kg Bersertifikat Damkar + Hanger & Pin"
},
  {
  "id": "SMKK-58",
  "code": "SMKK.9.2",
  "name": "Alat Pemadam Api Ringan (APAR) Karbon Dioksida (CO2) 5 kg",
  "category": "DOKUMEN_K3",
  "unit": "tabung",
  "unitPrice": 650000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Tabung APAR CO2 5kg Standar Listrik & Ruang Mesin Bersertifikat"
},
  {
  "id": "SMKK-59",
  "code": "SMKK.9.3",
  "name": "Pengujian dan Pengukuran Kualitas Lingkungan Kerja (Udara Ambien, Kebisingan, Getaran)",
  "category": "DOKUMEN_K3",
  "unit": "titik",
  "unitPrice": 2400000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Jasa Uji Laboratorium Lingkungan Terakreditasi KAN + Sertifikat Hasil Uji"
},
  {
  "id": "SMKK-60",
  "code": "SMKK.9.4",
  "name": "Pengujian Kualitas Air Kerja dan Air Buangan Proyek",
  "category": "DOKUMEN_K3",
  "unit": "sampel",
  "unitPrice": 1250000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Analisis Laboratorium Parameter Fisika-Kimia Air Standar Baku Mutu"
},
  {
  "id": "SMKK-61",
  "code": "SMKK.9.5",
  "name": "Tempat Penampungan Sementara Limbah Bahan Berbahaya dan Beracun (TPS Limbah B3)",
  "category": "DOKUMEN_K3",
  "unit": "unit",
  "unitPrice": 3800000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Box TPS B3 Bersekat Plat Baja / Drum Penampung Tertutup"
},
  {
  "id": "SMKK-62",
  "code": "SMKK.9.6",
  "name": "Audit Internal Penerapan Sistem Manajemen Keselamatan Konstruksi (SMKK)",
  "category": "DOKUMEN_K3",
  "unit": "kegiatan",
  "unitPrice": 3500000,
  "mandatory": true,
  "regulationReference": "SE DJBK No. 47 Tahun 2026 Lampiran III",
  "specification": "Laporan Audit SMKK, Checklist Evaluasi & Dokumentasi"
}
];

export const SMKK_AHSP_ITEMS: NationalAHSPItem[] = [
  {
  "id": "SMKK-2026-0001",
  "code": "SMKK.1.1",
  "codeNormalized": "SMKK.1.1",
  "name": "Pembuatan Dokumen Rencana Keselamatan Konstruksi (RKK) dan RMPK",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "category": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "subCategory": "Penyusunan RKK & RMPK",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Ahli Keselamatan Konstruksi / Ahli K3",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 3500000,
      "total": 3500000
    },
    {
      "id": "l2",
      "code": "L02",
      "name": "Tenaga Administrasi / Drafter Dokumen",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 750000,
      "total": 750000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Penggandaan Dokumen RKK & RMPK (Hardcopy & Softcopy)",
      "unit": "buku",
      "coefficient": 3.0,
      "unitPrice": 85000,
      "total": 255000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 4250000,
  "totalMaterial": 255000,
  "totalEquipment": 0,
  "unitPrice": 4505000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0002",
  "code": "SMKK.1.2",
  "codeNormalized": "SMKK.1.2",
  "name": "Pembuatan Dokumen Rencana Kerja Pengelolaan Lingkungan (RKPPL)",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "category": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "subCategory": "Penyusunan Dokumen Lingkungan",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Ahli Lingkungan / Ahli K3",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 2800000,
      "total": 2800000
    },
    {
      "id": "l2",
      "code": "L02",
      "name": "Tenaga Administrasi Dokumen",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 500000,
      "total": 500000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Penggandaan Dokumen RKPPL Lengkap Matriks Pemantauan",
      "unit": "buku",
      "coefficient": 3.0,
      "unitPrice": 70000,
      "total": 210000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 3300000,
  "totalMaterial": 210000,
  "totalEquipment": 0,
  "unitPrice": 3510000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0003",
  "code": "SMKK.1.3",
  "codeNormalized": "SMKK.1.3",
  "name": "Pembuatan Dokumen Rencana Manajemen Lalu Lintas Pekerjaan (RMLLP)",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "category": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "subCategory": "Manajemen Lalu Lintas Proyek",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Ahli Manajemen Lalu Lintas / K3",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 3000000,
      "total": 3000000
    },
    {
      "id": "l2",
      "code": "L02",
      "name": "Drafter Layout Rekayasa Lalu Lintas",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 550000,
      "total": 550000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Penggandaan Dokumen RMLLP & Gambar Skema Rambu",
      "unit": "buku",
      "coefficient": 3.0,
      "unitPrice": 70000,
      "total": 210000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 3550000,
  "totalMaterial": 210000,
  "totalEquipment": 0,
  "unitPrice": 3760000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0004",
  "code": "SMKK.1.4",
  "codeNormalized": "SMKK.1.4",
  "name": "Penyusunan Prosedur Kerja dan Instruksi Kerja (IK) Konstruksi (Minimal 12 Prosedur)",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "category": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "subCategory": "SOP & Instruksi Kerja",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Petugas Keselamatan Konstruksi",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 2200000,
      "total": 2200000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Penggandaan Buku SOP/IK Kerja Aman",
      "unit": "set",
      "coefficient": 3.0,
      "unitPrice": 100000,
      "total": 300000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 2200000,
  "totalMaterial": 300000,
  "totalEquipment": 0,
  "unitPrice": 2500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0005",
  "code": "SMKK.1.5",
  "codeNormalized": "SMKK.1.5",
  "name": "Penyusunan Pelaporan Bulanan Penerapan SMKK",
  "unit": "bulan",
  "domain": "SMKK",
  "subDomain": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "category": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "subCategory": "Laporan SMKK Berkala",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Petugas Keselamatan Konstruksi",
      "unit": "OB",
      "coefficient": 0.25,
      "unitPrice": 2500000,
      "total": 625000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Penggandaan & Penjilidan Laporan Bulanan SMKK (3 Rangkap)",
      "unit": "buku",
      "coefficient": 3.0,
      "unitPrice": 75000,
      "total": 225000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 625000,
  "totalMaterial": 225000,
  "totalEquipment": 0,
  "unitPrice": 850000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0006",
  "code": "SMKK.1.6",
  "codeNormalized": "SMKK.1.6",
  "name": "Penyiapan Formulir Izin Kerja (Permit to Work) dan Lembar Pemeriksaan SMKK",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "category": "ELEMEN 1 - PENYIAPAN DOKUMEN SMKK",
  "subCategory": "Formulir & Administrasi K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Pencetakan Formulir Izin Kerja Ketinggian/Panas/Galian/Confined Space (500 Lembar)",
      "unit": "rim",
      "coefficient": 1.0,
      "unitPrice": 350000,
      "total": 350000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Checklist Inspeksi Harian & Papan Izin Kerja",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 300000,
      "total": 300000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 650000,
  "totalEquipment": 0,
  "unitPrice": 650000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0007",
  "code": "SMKK.2.1",
  "codeNormalized": "SMKK.2.1",
  "name": "Kegiatan Induksi Keselamatan Konstruksi (Safety Induction)",
  "unit": "kegiatan",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Safety Induction",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Petugas Keselamatan Konstruksi / Instruktur",
      "unit": "OH",
      "coefficient": 0.2,
      "unitPrice": 250000,
      "total": 50000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Kartu Induksi K3 (Safety Pass/ID Card K3)",
      "unit": "buah",
      "coefficient": 25.0,
      "unitPrice": 8000,
      "total": 200000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Konsumsi Ringan & Air Minum Peserta Induksi",
      "unit": "porsi",
      "coefficient": 25.0,
      "unitPrice": 8000,
      "total": 200000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 50000,
  "totalMaterial": 400000,
  "totalEquipment": 0,
  "unitPrice": 450000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0008",
  "code": "SMKK.2.2",
  "codeNormalized": "SMKK.2.2",
  "name": "Pengarahan Keselamatan Konstruksi (Toolbox Meeting / Safety Morning)",
  "unit": "bulan",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Toolbox Meeting",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Petugas Keselamatan Konstruksi",
      "unit": "kegiatan",
      "coefficient": 4.0,
      "unitPrice": 150000,
      "total": 600000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Materi TBM, Lembar Absensi & Konsumsi Air Minum",
      "unit": "paket",
      "coefficient": 4.0,
      "unitPrice": 150000,
      "total": 600000
    }
  ],
  "equipmentComponents": [
    {
      "id": "e1",
      "code": "E01",
      "name": "Megaphone / Portable Sound System",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 650000,
      "total": 650000
    }
  ],
  "totalLabor": 600000,
  "totalMaterial": 600000,
  "totalEquipment": 650000,
  "unitPrice": 1850000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0009",
  "code": "SMKK.2.3",
  "codeNormalized": "SMKK.2.3",
  "name": "Pelatihan dan Sertifikasi K3 Konstruksi Internal / Eksternal",
  "unit": "orang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Pelatihan Kompetensi K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Biaya Registrasi Pelatihan, Modul, Sertifikat K3 & Konsumsi",
      "unit": "paket",
      "coefficient": 1.0,
      "unitPrice": 1850000,
      "total": 1850000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 1850000,
  "totalEquipment": 0,
  "unitPrice": 1850000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0010",
  "code": "SMKK.2.4",
  "codeNormalized": "SMKK.2.4",
  "name": "Kegiatan Simulasi Tanggap Darurat dan Evakuasi (Emergency Drill)",
  "unit": "kegiatan",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Simulasi Tanggap Darurat",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Instruktur / Ahli Pemadam Kebakaran / K3",
      "unit": "kegiatan",
      "coefficient": 1.0,
      "unitPrice": 1500000,
      "total": 1500000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Refill APAR untuk Latihan Pemadaman",
      "unit": "tabung",
      "coefficient": 3.0,
      "unitPrice": 250000,
      "total": 750000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Smoke Bomb, Flare & Perlengkapan Simulasi",
      "unit": "paket",
      "coefficient": 1.0,
      "unitPrice": 450000,
      "total": 450000
    },
    {
      "id": "m3",
      "code": "M03",
      "name": "Konsumsi & Air Mineral Peserta Simulasi",
      "unit": "porsi",
      "coefficient": 50.0,
      "unitPrice": 10000,
      "total": 500000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 1500000,
  "totalMaterial": 1700000,
  "totalEquipment": 0,
  "unitPrice": 3200000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0011",
  "code": "SMKK.2.5",
  "codeNormalized": "SMKK.2.5",
  "name": "Spanduk (Banner) Keselamatan Konstruksi Ukuran 1 x 4 meter",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Promosi & Kampanye K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Pekerja Lapangan (Pemasangan)",
      "unit": "OH",
      "coefficient": 0.1,
      "unitPrice": 135000,
      "total": 13500
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Banner Flexi 380 gsm Cetak High-Res 1x4m + Ring Mata Ayam",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 145000,
      "total": 145000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Tali Pengikat & Kayu Kaso Penyangga",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 25000,
      "total": 25000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 13500,
  "totalMaterial": 170000,
  "totalEquipment": 0,
  "unitPrice": 183500,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0012",
  "code": "SMKK.2.6",
  "codeNormalized": "SMKK.2.6",
  "name": "Poster / Leaflet / Brosur Keselamatan Konstruksi",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Promosi & Kampanye K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Poster K3 Art Carton A2 Laminasi Glossy / Frame Akrilik",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 45000,
      "total": 45000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 45000,
  "totalEquipment": 0,
  "unitPrice": 45000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0013",
  "code": "SMKK.2.7",
  "codeNormalized": "SMKK.2.7",
  "name": "Papan Informasi Keselamatan Konstruksi (Safety Board) Ukuran 1.2 x 2.4 meter",
  "unit": "unit",
  "domain": "SMKK",
  "subDomain": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "category": "ELEMEN 2 - SOSIALISASI, PROMOSI & PELATIHAN K3",
  "subCategory": "Papan Informasi K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Tukang Kayu / Besi",
      "unit": "OH",
      "coefficient": 0.5,
      "unitPrice": 180000,
      "total": 90000
    },
    {
      "id": "l2",
      "code": "L02",
      "name": "Pekerja Lapangan",
      "unit": "OH",
      "coefficient": 0.5,
      "unitPrice": 135000,
      "total": 67500
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Papan Multiplex 18mm / Plat Seng Rangka Besi Hollow",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 950000,
      "total": 950000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Visual Branding Rambu Statistik Zero Accident & Kebijakan K3",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 600000,
      "total": 600000
    },
    {
      "id": "m3",
      "code": "M03",
      "name": "Cat & Tiang Penyangga Pipa Galvanis dia. 2\"",
      "unit": "batang",
      "coefficient": 2.0,
      "unitPrice": 140000,
      "total": 280000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 157500,
  "totalMaterial": 1830000,
  "totalEquipment": 0,
  "unitPrice": 1987500,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0014",
  "code": "SMKK.3.1",
  "codeNormalized": "SMKK.3.1",
  "name": "Topi Pelindung (Safety Helmet) SNI ISO 3873 + Tali Dagu (Chin Strap)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Safety Helmet Bahan ABS High-Impact SNI dengan Fast-Trac Inner",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 65000,
      "total": 65000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 65000,
  "totalEquipment": 0,
  "unitPrice": 65000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0015",
  "code": "SMKK.3.2",
  "codeNormalized": "SMKK.3.2",
  "name": "Kacamata Pengaman (Safety Goggles / Safety Glasses ANSI Z87.1)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Safety Goggles Polycarbonate Anti-Scratch & Anti-Fog",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 35000,
      "total": 35000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 35000,
  "totalEquipment": 0,
  "unitPrice": 35000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0016",
  "code": "SMKK.3.3",
  "codeNormalized": "SMKK.3.3",
  "name": "Pelindung Wajah Penuh (Face Shield) untuk Pekerjaan Gerinda & Las",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Clear Polycarbonate Face Shield with Headgear Adjustable",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 95000,
      "total": 95000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 95000,
  "totalEquipment": 0,
  "unitPrice": 95000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0017",
  "code": "SMKK.3.4",
  "codeNormalized": "SMKK.3.4",
  "name": "Masker Pernafasan Partikulat (Masker N95 / KN95) SNI",
  "unit": "box",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Masker Debu & Partikel N95 (Isi 20 pcs/box)",
      "unit": "box",
      "coefficient": 1.0,
      "unitPrice": 125000,
      "total": 125000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 125000,
  "totalEquipment": 0,
  "unitPrice": 125000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0018",
  "code": "SMKK.3.5",
  "codeNormalized": "SMKK.3.5",
  "name": "Respirator Cartridge Ganda untuk Pekerjaan Kimia / Pengecatan / Gas",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Half Face Respirator Dual Filter Cartridge Organic Vapor/Particulate",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 275000,
      "total": 275000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 275000,
  "totalEquipment": 0,
  "unitPrice": 275000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0019",
  "code": "SMKK.3.6",
  "codeNormalized": "SMKK.3.6",
  "name": "Pelindung Telinga (Ear Plug Polyurethane SNR 35 dB)",
  "unit": "pasang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Ear Plug Busa Lembut dengan Tali Penghubung",
      "unit": "pasang",
      "coefficient": 1.0,
      "unitPrice": 12000,
      "total": 12000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 12000,
  "totalEquipment": 0,
  "unitPrice": 12000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0020",
  "code": "SMKK.3.7",
  "codeNormalized": "SMKK.3.7",
  "name": "Penutup Telinga (Ear Muff) Heavy Duty NRR 28 dB",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Ear Muff Adjustable Headband Standar Industri",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 115000,
      "total": 115000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 115000,
  "totalEquipment": 0,
  "unitPrice": 115000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0021",
  "code": "SMKK.3.8",
  "codeNormalized": "SMKK.3.8",
  "name": "Sarung Tangan Keselamatan Kulit / Las (Welding Leather Gloves)",
  "unit": "pasang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Sarung Tangan Kulit Sapi Split Panjang 14-16 Inci",
      "unit": "pasang",
      "coefficient": 1.0,
      "unitPrice": 45000,
      "total": 45000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 45000,
  "totalEquipment": 0,
  "unitPrice": 45000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0022",
  "code": "SMKK.3.9",
  "codeNormalized": "SMKK.3.9",
  "name": "Sarung Tangan Keselamatan Karet / Nitrile Tahan Kimia",
  "unit": "pasang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Sarung Tangan Heavy Duty Nitrile/Neoprene Resistant",
      "unit": "pasang",
      "coefficient": 1.0,
      "unitPrice": 32000,
      "total": 32000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 32000,
  "totalEquipment": 0,
  "unitPrice": 32000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0023",
  "code": "SMKK.3.10",
  "codeNormalized": "SMKK.3.10",
  "name": "Sarung Tangan Rajut Katun Bintik Karet (Dotting Cotton Gloves)",
  "unit": "lusin",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Sarung Tangan Benang Rajut 8 Benang Bintik Kuning (Isi 12 pasang)",
      "unit": "lusin",
      "coefficient": 1.0,
      "unitPrice": 65000,
      "total": 65000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 65000,
  "totalEquipment": 0,
  "unitPrice": 65000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0024",
  "code": "SMKK.3.11",
  "codeNormalized": "SMKK.3.11",
  "name": "Sepatu Keselamatan (Safety Shoes Steel Toe Cap SNI 7079)",
  "unit": "pasang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Sepatu Safety Kulit Asli dengan Ujung Baja 200J & Sol PU Anti-Slip",
      "unit": "pasang",
      "coefficient": 1.0,
      "unitPrice": 285000,
      "total": 285000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 285000,
  "totalEquipment": 0,
  "unitPrice": 285000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0025",
  "code": "SMKK.3.12",
  "codeNormalized": "SMKK.3.12",
  "name": "Sepatu Bot Karet Keselamatan (Safety Rubber Boots Steel Toe)",
  "unit": "pasang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Boots Karet PVC Tahan Air, Kimia, Lumpur dengan Steel Toe Cap",
      "unit": "pasang",
      "coefficient": 1.0,
      "unitPrice": 165000,
      "total": 165000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 165000,
  "totalEquipment": 0,
  "unitPrice": 165000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0026",
  "code": "SMKK.3.13",
  "codeNormalized": "SMKK.3.13",
  "name": "Rompi Keselamatan Reflektif High-Visibility (Safety Vest Hi-Vis Kelas 2)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Rompi Jaring Polyester Fluorescent dengan Pita Scotchlite 5cm",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 45000,
      "total": 45000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 45000,
  "totalEquipment": 0,
  "unitPrice": 45000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0027",
  "code": "SMKK.3.14",
  "codeNormalized": "SMKK.3.14",
  "name": "Sabuk dan Tali Keselamatan Tubuh Penuh (Full Body Harness Double Lanyard + Absorber)",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Full Body Harness 5 Point Attachment + Double Big Hook & Shock Absorber EN361",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 485000,
      "total": 485000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 485000,
  "totalEquipment": 0,
  "unitPrice": 485000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0028",
  "code": "SMKK.3.15",
  "codeNormalized": "SMKK.3.15",
  "name": "Pelampung Keselamatan (Life Jacket / Life Vest) Standar SOLAS",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Life Jacket Pelampung Busa Foam Daya Apung 150N Lengkap Peluit & Reflektor",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 225000,
      "total": 225000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 225000,
  "totalEquipment": 0,
  "unitPrice": 225000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0029",
  "code": "SMKK.3.16",
  "codeNormalized": "SMKK.3.16",
  "name": "Jas Hujan Keselamatan (Safety Raincoat Setelan)",
  "unit": "set",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Diri (APD)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Jas Hujan Setelan Baju + Celana PVC Tebal dengan Scotchlite",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 120000,
      "total": 120000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 120000,
  "totalEquipment": 0,
  "unitPrice": 120000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0030",
  "code": "SMKK.3.17",
  "codeNormalized": "SMKK.3.17",
  "name": "Jaring Pengaman Konstruksi (Safety Net) Ukuran Mesh 5 x 5 cm",
  "unit": "m2",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Kerja (APK)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Pekerja Lapangan (Pemasangan)",
      "unit": "OH",
      "coefficient": 0.04,
      "unitPrice": 135000,
      "total": 5400
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Jaring Pengaman Polietilena / Nylon Anyam Tambang Kuat 6mm",
      "unit": "m2",
      "coefficient": 1.05,
      "unitPrice": 28000,
      "total": 29400
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Tali Pengikat & Klem Baja Penahan",
      "unit": "ls",
      "coefficient": 1.0,
      "unitPrice": 5000,
      "total": 5000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 5400,
  "totalMaterial": 34400,
  "totalEquipment": 0,
  "unitPrice": 39800,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0031",
  "code": "SMKK.3.18",
  "codeNormalized": "SMKK.3.18",
  "name": "Tali Keselamatan Horisontal/Vertikal (Life Line Wire Rope dia. 8-10 mm)",
  "unit": "m'",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Kerja (APK)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Tukang Besi",
      "unit": "OH",
      "coefficient": 0.03,
      "unitPrice": 185000,
      "total": 5550
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Kawat Seling Baja Galvanis dia. 8mm (Wire Rope)",
      "unit": "m'",
      "coefficient": 1.05,
      "unitPrice": 32000,
      "total": 33600
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Spanscrew / Turnbuckle & Kuku Macan (Wire Clip)",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 10000,
      "total": 10000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 5550,
  "totalMaterial": 43600,
  "totalEquipment": 0,
  "unitPrice": 49150,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0032",
  "code": "SMKK.3.19",
  "codeNormalized": "SMKK.3.19",
  "name": "Pagar Pengaman Sementara / Safety Railing Tinggi 1.1 meter",
  "unit": "m'",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Kerja (APK)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Tukang Besi / Kayu",
      "unit": "OH",
      "coefficient": 0.15,
      "unitPrice": 180000,
      "total": 27000
    },
    {
      "id": "l2",
      "code": "L02",
      "name": "Pekerja Lapangan",
      "unit": "OH",
      "coefficient": 0.15,
      "unitPrice": 135000,
      "total": 20250
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Pipa Galvanis dia. 1.5\" / Kayu Kaso 5/7 Dua Jalur",
      "unit": "m'",
      "coefficient": 1.0,
      "unitPrice": 95000,
      "total": 95000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Base Plate, Angkur & Cat Kuning-Hitam Reflektif",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 25000,
      "total": 25000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 47250,
  "totalMaterial": 120000,
  "totalEquipment": 0,
  "unitPrice": 167250,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0033",
  "code": "SMKK.3.20",
  "codeNormalized": "SMKK.3.20",
  "name": "Kerucut Lalu Lintas / Pembatas Area (Traffic Cone Tinggi 75 cm)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Kerja (APK)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Traffic Cone Bahan Rubber PVC Fleksibel Heavy Base + 2 Pita Scotchlite",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 135000,
      "total": 135000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 135000,
  "totalEquipment": 0,
  "unitPrice": 135000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0034",
  "code": "SMKK.3.21",
  "codeNormalized": "SMKK.3.21",
  "name": "Pita Pengaman Pembatas (Safety Barricade Warning Tape Kuning-Hitam / Merah-Putih)",
  "unit": "roll",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Kerja (APK)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Barricade Tape Non-Adhesive Lebar 3 Inci Panjang 300 meter",
      "unit": "roll",
      "coefficient": 1.0,
      "unitPrice": 55000,
      "total": 55000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 55000,
  "totalEquipment": 0,
  "unitPrice": 55000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0035",
  "code": "SMKK.3.22",
  "codeNormalized": "SMKK.3.22",
  "name": "Barikade Pembatas Jalan Plastik (Water Barrier Isi Air / Pasir)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "category": "ELEMEN 3 - ALAT PELINDUNG KERJA (APK) & ALAT PELINDUNG DIRI (APD)",
  "subCategory": "Alat Pelindung Kerja (APK)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Road Barrier Plastik HDPE Dimensi 120 x 80 x 50 cm Interlocking System",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 485000,
      "total": 485000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 485000,
  "totalEquipment": 0,
  "unitPrice": 485000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0036",
  "code": "SMKK.4.1",
  "codeNormalized": "SMKK.4.1",
  "name": "Asuransi Tenaga Kerja Konstruksi (BPJS Ketenagakerjaan Program JKK & JKM Proyek)",
  "unit": "ls",
  "domain": "SMKK",
  "subDomain": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "category": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "subCategory": "BPJS Ketenagakerjaan Konstruksi",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Premi BPJS Ketenagakerjaan Paket Jaminan Kecelakaan Kerja & Jematian",
      "unit": "paket",
      "coefficient": 1.0,
      "unitPrice": 8500000,
      "total": 8500000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 8500000,
  "totalEquipment": 0,
  "unitPrice": 8500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0037",
  "code": "SMKK.4.2",
  "codeNormalized": "SMKK.4.2",
  "name": "Asuransi Rekayasa / Contractor's All Risks (CAR) dan Third Party Liability (TPL)",
  "unit": "ls",
  "domain": "SMKK",
  "subDomain": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "category": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "subCategory": "Asuransi Proyek (CAR/TPL)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Polis Asuransi CAR & Kerugian Pihak Ketiga Selama Masa Konstruksi",
      "unit": "paket",
      "coefficient": 1.0,
      "unitPrice": 12500000,
      "total": 12500000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 12500000,
  "totalEquipment": 0,
  "unitPrice": 12500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0038",
  "code": "SMKK.4.3",
  "codeNormalized": "SMKK.4.3",
  "name": "Pengurusan Surat Izin Laik Operasi (SILO) dan Uji Riksa Alat Berat Konstruksi",
  "unit": "alat",
  "domain": "SMKK",
  "subDomain": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "category": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "subCategory": "Sertifikasi Kelaikan Alat (SILO)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Biaya Uji Riksa PJK3 Resmi & Penerbitan Sertifikat SILO Kemnaker",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 3500000,
      "total": 3500000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 3500000,
  "totalEquipment": 0,
  "unitPrice": 3500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0039",
  "code": "SMKK.4.4",
  "codeNormalized": "SMKK.4.4",
  "name": "Pengurusan Surat Izin Operator (SIO) / Lisensi K3 Operator Alat Berat",
  "unit": "orang",
  "domain": "SMKK",
  "subDomain": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "category": "ELEMEN 4 - ASURANSI & PERIZINAN KESELAMATAN",
  "subCategory": "Lisensi Operator (SIO)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Biaya Verifikasi & Penerbitan Lisensi K3 Operator Alat Berat",
      "unit": "orang",
      "coefficient": 1.0,
      "unitPrice": 2200000,
      "total": 2200000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 2200000,
  "totalEquipment": 0,
  "unitPrice": 2200000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0040",
  "code": "SMKK.5.1",
  "codeNormalized": "SMKK.5.1",
  "name": "Ahli Utama Keselamatan Konstruksi (Ahli K3 Konstruksi Utama)",
  "unit": "OB",
  "domain": "SMKK",
  "subDomain": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "subCategory": "Tenaga Ahli K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Ahli Utama K3 Konstruksi Bersertifikat BNSP / LPJK",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 18500000,
      "total": 18500000
    }
  ],
  "materialComponents": [],
  "equipmentComponents": [],
  "totalLabor": 18500000,
  "totalMaterial": 0,
  "totalEquipment": 0,
  "unitPrice": 18500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0041",
  "code": "SMKK.5.2",
  "codeNormalized": "SMKK.5.2",
  "name": "Ahli Madya Keselamatan Konstruksi (Ahli K3 Konstruksi Madya)",
  "unit": "OB",
  "domain": "SMKK",
  "subDomain": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "subCategory": "Tenaga Ahli K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Ahli Madya K3 Konstruksi Bersertifikat BNSP / LPJK",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 12500000,
      "total": 12500000
    }
  ],
  "materialComponents": [],
  "equipmentComponents": [],
  "totalLabor": 12500000,
  "totalMaterial": 0,
  "totalEquipment": 0,
  "unitPrice": 12500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0042",
  "code": "SMKK.5.3",
  "codeNormalized": "SMKK.5.3",
  "name": "Ahli Muda Keselamatan Konstruksi (Ahli K3 Konstruksi Muda)",
  "unit": "OB",
  "domain": "SMKK",
  "subDomain": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "subCategory": "Tenaga Ahli K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Ahli Muda K3 Konstruksi Bersertifikat BNSP / LPJK",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 8500000,
      "total": 8500000
    }
  ],
  "materialComponents": [],
  "equipmentComponents": [],
  "totalLabor": 8500000,
  "totalMaterial": 0,
  "totalEquipment": 0,
  "unitPrice": 8500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0043",
  "code": "SMKK.5.4",
  "codeNormalized": "SMKK.5.4",
  "name": "Petugas Keselamatan Konstruksi / Safety Officer Lapangan",
  "unit": "OB",
  "domain": "SMKK",
  "subDomain": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "subCategory": "Petugas K3 Lapangan",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Petugas Keselamatan Konstruksi Bersertifikat Kemenaker/PUPR",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 5500000,
      "total": 5500000
    }
  ],
  "materialComponents": [],
  "equipmentComponents": [],
  "totalLabor": 5500000,
  "totalMaterial": 0,
  "totalEquipment": 0,
  "unitPrice": 5500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0044",
  "code": "SMKK.5.5",
  "codeNormalized": "SMKK.5.5",
  "name": "Petugas Pertolongan Pertama Pada Kecelakaan (Petugas P3K Proyek)",
  "unit": "OB",
  "domain": "SMKK",
  "subDomain": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "subCategory": "Petugas P3K & Medis",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Petugas P3K Bersertifikat Lisensi Kemnaker",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 4200000,
      "total": 4200000
    }
  ],
  "materialComponents": [],
  "equipmentComponents": [],
  "totalLabor": 4200000,
  "totalMaterial": 0,
  "totalEquipment": 0,
  "unitPrice": 4200000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0045",
  "code": "SMKK.5.6",
  "codeNormalized": "SMKK.5.6",
  "name": "Petugas Pengatur Lalu Lintas Proyek (Flagman)",
  "unit": "OB",
  "domain": "SMKK",
  "subDomain": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 5 - PERSONEL KESELAMATAN KONSTRUKSI",
  "subCategory": "Flagman Lalu Lintas",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Flagman / Pengatur Lalu Lintas Bersertifikat Pelatihan",
      "unit": "OB",
      "coefficient": 1.0,
      "unitPrice": 3800000,
      "total": 3800000
    }
  ],
  "materialComponents": [],
  "equipmentComponents": [],
  "totalLabor": 3800000,
  "totalMaterial": 0,
  "totalEquipment": 0,
  "unitPrice": 3800000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0046",
  "code": "SMKK.6.1",
  "codeNormalized": "SMKK.6.1",
  "name": "Peralatan Ruang Pos P3K / Klinik Darurat Lapangan",
  "unit": "unit",
  "domain": "SMKK",
  "subDomain": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "category": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "subCategory": "Pos P3K Proyek",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Tempat Tidur Periksa Pasien + Matras & Bantal",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 1850000,
      "total": 1850000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Meja, Kursi Dokter & Lemari Obat Kaca Kunci",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 1450000,
      "total": 1450000
    },
    {
      "id": "m3",
      "code": "M03",
      "name": "Tensimeter Digital, Termometer Infrared, Timbangan Badan",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 900000,
      "total": 900000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 4200000,
  "totalEquipment": 0,
  "unitPrice": 4200000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0047",
  "code": "SMKK.6.2",
  "codeNormalized": "SMKK.6.2",
  "name": "Kotak P3K Standar Tipe B Lengkap dengan Isi (Permenakertrans No. 15/2008)",
  "unit": "unit",
  "domain": "SMKK",
  "subDomain": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "category": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "subCategory": "Kotak & Obat P3K",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Kotak P3K Dinding Lengkap Isi Kasa Steril, Perban, Plester, Antiseptik, Bidai, Gunting, Pinset",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 650000,
      "total": 650000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 650000,
  "totalEquipment": 0,
  "unitPrice": 650000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0048",
  "code": "SMKK.6.3",
  "codeNormalized": "SMKK.6.3",
  "name": "Tandu Darurat Lipat (Foldable Emergency Stretcher Aluminium)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "category": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "subCategory": "Peralatan Evakuasi Medis",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Tandu Lipat Rangka Aluminium Alloy Beban Maksimal 160 kg",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 750000,
      "total": 750000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 750000,
  "totalEquipment": 0,
  "unitPrice": 750000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0049",
  "code": "SMKK.6.4",
  "codeNormalized": "SMKK.6.4",
  "name": "Tabung Oksigen Medis Portable Lengkap dengan Regulator & Masker (1 m3)",
  "unit": "unit",
  "domain": "SMKK",
  "subDomain": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "category": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "subCategory": "Oksigen Darurat",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Tabung Gas Oksigen Medis 1m3 + Trolley Roda + Regulator Flowmeter & Nasal Cannula",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 1450000,
      "total": 1450000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 1450000,
  "totalEquipment": 0,
  "unitPrice": 1450000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0050",
  "code": "SMKK.6.5",
  "codeNormalized": "SMKK.6.5",
  "name": "Fasilitas Cuci Tangan Portabel (Wastafel Portabel Injak + Sabun)",
  "unit": "unit",
  "domain": "SMKK",
  "subDomain": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "category": "ELEMEN 6 - FASILITAS, SARANA & ALAT KESEHATAN",
  "subCategory": "Sanitasi & Kebersihan",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Wastafel Portabel Sistem Pedal Injak Tanpa Sentuh + Tangki Air & Penampung",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 850000,
      "total": 850000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 850000,
  "totalEquipment": 0,
  "unitPrice": 850000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0051",
  "code": "SMKK.7.1",
  "codeNormalized": "SMKK.7.1",
  "name": "Rambu Peringatan Keselamatan Konstruksi (Ukuran 60 x 60 cm)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "category": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "subCategory": "Rambu Peringatan K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Pekerja Lapangan (Pemasangan)",
      "unit": "OH",
      "coefficient": 0.15,
      "unitPrice": 135000,
      "total": 20250
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Daun Rambu Plat Aluminium 1.2mm + Sticker Reflective Sheet Engineering Grade",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 165000,
      "total": 165000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Tiang Pipa Galvanis dia. 2\" + Pondasi Cor Mini",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 40000,
      "total": 40000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 20250,
  "totalMaterial": 205000,
  "totalEquipment": 0,
  "unitPrice": 225250,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0052",
  "code": "SMKK.7.2",
  "codeNormalized": "SMKK.7.2",
  "name": "Rambu Larangan / Perintah Wajib APD (Ukuran 60 x 60 cm)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "category": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "subCategory": "Rambu Mandatory K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Pekerja Lapangan (Pemasangan)",
      "unit": "OH",
      "coefficient": 0.15,
      "unitPrice": 135000,
      "total": 20250
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Daun Rambu Bulat Plat Aluminium 1.2mm + Sticker Reflective Sheet EGP",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 165000,
      "total": 165000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Tiang Pipa Galvanis dia. 2\" + Braket Klem",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 40000,
      "total": 40000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 20250,
  "totalMaterial": 205000,
  "totalEquipment": 0,
  "unitPrice": 225250,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0053",
  "code": "SMKK.7.3",
  "codeNormalized": "SMKK.7.3",
  "name": "Rambu Petunjuk Arah dan Jalur Evakuasi Proyek Glow in the Dark",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "category": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "subCategory": "Rambu Evakuasi",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Rambu Akrilik / Plat Seng Fosfor Photoluminescent Menyala Dalam Gelap",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 135000,
      "total": 135000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 135000,
  "totalEquipment": 0,
  "unitPrice": 135000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0054",
  "code": "SMKK.7.4",
  "codeNormalized": "SMKK.7.4",
  "name": "Tongkat Pengatur Lalu Lintas LED (Traffic Baton Light)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "category": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "subCategory": "Alat Pengatur Lalu Lintas",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Lampu Tongkat Parkir LED Magnetik + Baterai Isi Ulang",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 85000,
      "total": 85000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 85000,
  "totalEquipment": 0,
  "unitPrice": 85000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0055",
  "code": "SMKK.7.5",
  "codeNormalized": "SMKK.7.5",
  "name": "Lampu Rotary Peringatan Bahaya (Warning Strobe Beacon Light 12/24V)",
  "unit": "buah",
  "domain": "SMKK",
  "subDomain": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "category": "ELEMEN 7 - RAMBU & PERLENGKAPAN LALU LINTAS (RMLLP)",
  "subCategory": "Lampu Peringatan Bahaya",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Lampu Rotary LED Flash Kuning Amber Dudukan Magnetik / Tiang",
      "unit": "buah",
      "coefficient": 1.0,
      "unitPrice": 245000,
      "total": 245000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 245000,
  "totalEquipment": 0,
  "unitPrice": 245000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0056",
  "code": "SMKK.8.1",
  "codeNormalized": "SMKK.8.1",
  "name": "Jasa Konsultansi Ahli Keselamatan Konstruksi Spesialis",
  "unit": "kegiatan",
  "domain": "SMKK",
  "subDomain": "ELEMEN 8 - KONSULTASI AHLI KESELAMATAN KONSTRUKSI",
  "category": "ELEMEN 8 - KONSULTASI AHLI KESELAMATAN KONSTRUKSI",
  "subCategory": "Konsultasi Ahli K3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Tenaga Ahli Senior K3 / Spesialis Struktur & Geoteknik K3",
      "unit": "kegiatan",
      "coefficient": 1.0,
      "unitPrice": 6000000,
      "total": 6000000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Laporan Rekomendasi Teknis Pengendalian Risiko Tinggi",
      "unit": "buku",
      "coefficient": 1.0,
      "unitPrice": 500000,
      "total": 500000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 6000000,
  "totalMaterial": 500000,
  "totalEquipment": 0,
  "unitPrice": 6500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0057",
  "code": "SMKK.9.1",
  "codeNormalized": "SMKK.9.1",
  "name": "Alat Pemadam Api Ringan (APAR) Dry Chemical Powder 6 kg",
  "unit": "tabung",
  "domain": "SMKK",
  "subDomain": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "category": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "subCategory": "Alat Pemadam Api (APAR)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Tabung APAR ABC Dry Chemical Powder 6kg Bersertifikat Damkar + Hanger & Pin",
      "unit": "tabung",
      "coefficient": 1.0,
      "unitPrice": 385000,
      "total": 385000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 385000,
  "totalEquipment": 0,
  "unitPrice": 385000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0058",
  "code": "SMKK.9.2",
  "codeNormalized": "SMKK.9.2",
  "name": "Alat Pemadam Api Ringan (APAR) Karbon Dioksida (CO2) 5 kg",
  "unit": "tabung",
  "domain": "SMKK",
  "subDomain": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "category": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "subCategory": "Alat Pemadam Api (APAR)",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Tabung APAR CO2 5kg Standar Listrik & Ruang Mesin Bersertifikat",
      "unit": "tabung",
      "coefficient": 1.0,
      "unitPrice": 650000,
      "total": 650000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 650000,
  "totalEquipment": 0,
  "unitPrice": 650000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0059",
  "code": "SMKK.9.3",
  "codeNormalized": "SMKK.9.3",
  "name": "Pengujian dan Pengukuran Kualitas Lingkungan Kerja (Udara Ambien, Kebisingan, Getaran)",
  "unit": "titik",
  "domain": "SMKK",
  "subDomain": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "category": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "subCategory": "Uji Lingkungan Kerja",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Jasa Uji Laboratorium Lingkungan Terakreditasi KAN + Sertifikat Hasil Uji",
      "unit": "titik",
      "coefficient": 1.0,
      "unitPrice": 2400000,
      "total": 2400000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 2400000,
  "totalEquipment": 0,
  "unitPrice": 2400000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0060",
  "code": "SMKK.9.4",
  "codeNormalized": "SMKK.9.4",
  "name": "Pengujian Kualitas Air Kerja dan Air Buangan Proyek",
  "unit": "sampel",
  "domain": "SMKK",
  "subDomain": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "category": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "subCategory": "Uji Air & Limbah",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Analisis Laboratorium Parameter Fisika-Kimia Air Standar Baku Mutu",
      "unit": "sampel",
      "coefficient": 1.0,
      "unitPrice": 1250000,
      "total": 1250000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 0,
  "totalMaterial": 1250000,
  "totalEquipment": 0,
  "unitPrice": 1250000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0061",
  "code": "SMKK.9.5",
  "codeNormalized": "SMKK.9.5",
  "name": "Tempat Penampungan Sementara Limbah Bahan Berbahaya dan Beracun (TPS Limbah B3)",
  "unit": "unit",
  "domain": "SMKK",
  "subDomain": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "category": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "subCategory": "Pengelolaan Limbah B3",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Tukang Besi / Kayu",
      "unit": "OH",
      "coefficient": 1.0,
      "unitPrice": 180000,
      "total": 180000
    },
    {
      "id": "l2",
      "code": "L02",
      "name": "Pekerja Lapangan",
      "unit": "OH",
      "coefficient": 2.0,
      "unitPrice": 135000,
      "total": 270000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Box TPS B3 Bersekat Plat Baja / Drum Penampung Tertutup",
      "unit": "unit",
      "coefficient": 1.0,
      "unitPrice": 2200000,
      "total": 2200000
    },
    {
      "id": "m2",
      "code": "M02",
      "name": "Spill Kit Penanganan Tumpahan Oli/Bahan Kimia",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 850000,
      "total": 850000
    },
    {
      "id": "m3",
      "code": "M03",
      "name": "Simbol & Label Limbah B3 Standar KLHK",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 300000,
      "total": 300000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 450000,
  "totalMaterial": 3350000,
  "totalEquipment": 0,
  "unitPrice": 3800000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
},
  {
  "id": "SMKK-2026-0062",
  "code": "SMKK.9.6",
  "codeNormalized": "SMKK.9.6",
  "name": "Audit Internal Penerapan Sistem Manajemen Keselamatan Konstruksi (SMKK)",
  "unit": "kegiatan",
  "domain": "SMKK",
  "subDomain": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "category": "ELEMEN 9 - PENGENDALIAN RISIKO & PENGUJIAN LINGKUNGAN",
  "subCategory": "Audit Internal SMKK",
  "version": "2026",
  "year": 2026,
  "normativeStatus": "Normatif",
  "method": "Manual",
  "sourceId": "SRC-SMKK-2026",
  "sourceDocument": "Lampiran III Biaya Penerapan SMKK (SE DJBK No. 47/SE/Dk/2026)",
  "sourcePage": 1,
  "status": "VERIFIED",
  "laborComponents": [
    {
      "id": "l1",
      "code": "L01",
      "name": "Auditor Internal K3 Konstruksi",
      "unit": "kegiatan",
      "coefficient": 1.0,
      "unitPrice": 3000000,
      "total": 3000000
    }
  ],
  "materialComponents": [
    {
      "id": "m1",
      "code": "M01",
      "name": "Laporan Audit SMKK, Checklist Evaluasi & Dokumentasi",
      "unit": "set",
      "coefficient": 1.0,
      "unitPrice": 500000,
      "total": 500000
    }
  ],
  "equipmentComponents": [],
  "totalLabor": 3000000,
  "totalMaterial": 500000,
  "totalEquipment": 0,
  "unitPrice": 3500000,
  "lastUpdated": "2026-02-18",
  "dataQualityScore": 100
}
];
